default_platform(:android)

platform :android do

  desc "🧪 Run unit tests"
  lane :test do
    gradle(task: "test")
  end

  desc "🚀 Deploy DEVELOPMENT flavor to Internal Testing"
lane :development_internal do
  gradle(task: "clean")

  android_set_version_code(
    gradle_file: "app/build.gradle",
    version_code: android_get_version_code(
      gradle_file: "app/build.gradle"
    ).to_i + 1
  )

  gradle(
    task: "bundle",
    flavor: "development",
    build_type: "Release"
  )

  upload_to_play_store(
    track: 'internal',
    json_key: "fastlane/keys/reactnativeignitekit-5b01e2ebe216.json",
    package_name: "com.snapbiodata.app",
    skip_upload_apk: true,
    skip_upload_screenshots: false
  )
end


  desc "🧪 Deploy SIT flavor to Open Testing (Beta)"
  lane :sit_beta do
    gradle(task: "clean")

    android_set_version_code(
      gradle_file: "app/build.gradle",
      version_code: android_get_version_code(
        gradle_file: "app/build.gradle"
      ).to_i + 1
    )

    gradle(
      task: "bundle",
      flavor: "sit",
      build_type: "Release"
    )

    upload_to_play_store(
      track: 'beta',
      json_key: "fastlane/keys/reactnativeignitekit-5b01e2ebe216.json",
      package_name: "com.snapbiodata.app",
      skip_upload_apk: true,
      skip_upload_screenshots: false
    )
  end

  desc "🔒 Deploy UAT flavor to Closed Testing"
  lane :uat_closed do
    gradle(task: "clean")

    android_set_version_code(
      gradle_file: "app/build.gradle",
      version_code: android_get_version_code(
        gradle_file: "app/build.gradle"
      ).to_i + 1
    )

    gradle(
      task: "bundle",
      flavor: "uat",
      build_type: "Release"
    )

    upload_to_play_store(
      track: 'closed',
      json_key: "fastlane/keys/reactnativeignitekit-5b01e2ebe216.json",
      package_name: "com.snapbiodata.app",
      skip_upload_apk: true,
      skip_upload_screenshots: false
    )
  end

  desc "🏁 Deploy PRODUCTION flavor to Production"
  lane :production_release do
    gradle(task: "clean")

    android_set_version_code(
      gradle_file: "app/build.gradle",
      version_code: android_get_version_code(
        gradle_file: "app/build.gradle"
      ).to_i + 1
    )

    # 🧱 Optional: Build APK (for internal use)
    gradle(
      task: "assemble",
      flavor: "production",
      build_type: "Release"
    )

    # 🧱 Build AAB for Play Store
    gradle(
      task: "bundle",
      flavor: "production",
      build_type: "Release"
    )

    upload_to_play_store(
      track: 'production',
      json_key: "fastlane/keys/reactnativeignitekit-5b01e2ebe216.json",
      package_name: "com.snapbiodata.app",
      skip_upload_apk: true,
      skip_upload_screenshots: false
    )
  end

end
